---
name: Train Classifier
author: Christian Sargusingh
description: Trains a target classifer and compiles training data.
inputs:
  SLACK_IDENTIFIER:
    description: 'Slack channel webhook path'
    required: true
  MODEL:
    description: 'Target model for training'
    required: true
  ACCESS_KEY_ID:
    description: 'Incuvers ml-ci aws s3 user access key'
    required: true
  SECRET_ACCESS_KEY_ID:
    description: 'Incuvers ml-ci aws s3 user secret access key'
    required: true
  MODE:
    description: 'can only take on 'train' or 'eval' modes'
    default: 'train'
    required: false

runs:
  using: 'composite'
  steps:
    - name: build docker image target model
      working-directory: ${{ github.action_path }}
      run: ./scripts/build.sh
      shell: bash
    - name: run model container
      working-directory: ${{ github.action_path }}
      run: ./scripts/run.sh
      shell: bash
    - name: container cleanup
      run: docker image prune
      shell: bash
