---
name: Train Classifier 
author: Christian Sargusingh
description: Trains a new machine learning classifer and uploads the artefacts to github
inputs:
  SLACK_IDENTIFIER:
    description: 'Slack channel webhook path'
    required: true
  MODEL:
    description: 'train target model'
    required: true
  OUTPUT:
    description: 'training output directory'
    required: true

runs:
  using: 'composite'
  steps:
    - name: build docker image target model
      working-directory: ${{ github.action_path }}
      run: ./scripts/build.sh
      shell: bash
    - name: run model container
      working-directory: ${{ github.action_path }}
      run: ./scripts/run.sh
      shell: bash
    - name: prune
      run: docker image prune
      shell: bash