---
name: Train Classifier 
author: Christian Sargusingh
description: Trains a new machine learning classifer and uploads the artefacts to github
inputs:
  SLACK_IDENTIFIER:
    description: 'Slack channel webhook path'
    required: true
  MODEL:
    description: 'train target model'
    required: true
  OUTPUT:
    description: 'training output directory'
    required: true

runs:
  using: 'composite'
  steps:
    - name: build docker image target model
      env:
        MODEL: ${{ inputs.MODEL }}
        SLACK_IDENTIFIER: ${{ inputs.SLACK_IDENTIFIER }}
      working-directory: ${{ github.action_path }}
      run: ./scripts/build.sh
      shell: bash

    - name: run model container
      run: ${{ github.action_path }}/scripts/run.sh
      shell: bash
      env:
        OUTPUT: ${{ inputs.OUTPUT }}
        SLACK_IDENTIFIER: ${{ inputs.SLACK_IDENTIFIER }}
